### ISSUE TITLE
Plantage du programme

### ISSUE THREAD

**Issue by SarahMinich** [pagination-problem/2-tile#7]
J'ai écrit une routine `cplex_launch.py` qui, tant qu'on ne l'arrête pas, génère un Tree aléatoirement (avec un nombre de noeuds compris entre 5 et 26), trouve la solution optimale grâce à CPLEX et teste deux conditions (cf commit ef9921c).

Cette routine a pour but de vérifier deux intuitions que nous avons avec Imed. 

Cependant, la routine plante systématiquement au bout d'un certain nombre d'itérations (je n'ai pas vérifié si c'était toujours le même nombre -note à moi-même : à faire demain-) et je ne comprends pas pourquoi car lorsque je traite à part l'arbre qui est supposé avoir fait planter la routine, tout se passe très bien.

Ci-après, la trace obtenue lors du l'arrêt du programme.
```
[13, 24, 16, 3, 10, 24, 6, 6, 13, 18, 3, 15, 4, 22, 12, 18, 17, 0, 12, 11, 17, 22, 17]
CPLEX Error  1422: Could not open file 'saved_models/problematic_tree_1.lp' for writing.
Traceback (most recent call last):
  File "c:\Users\sarah\.vscode\extensions\ms-python.python-2020.3.69010\pythonFiles\ptvsd_launcher.py", line 48, in <module>
    main(ptvsdArgs)
  File "c:\Users\sarah\.vscode\extensions\ms-python.python-2020.3.69010\pythonFiles\lib\python\old_ptvsd\ptvsd\__main__.py", line 432, in main
    run()
  File "c:\Users\sarah\.vscode\extensions\ms-python.python-2020.3.69010\pythonFiles\lib\python\old_ptvsd\ptvsd\__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\sarah\Documents\These\Sub-problems\2-tiles\Tree\Programmation\2-tile\cplex_launch.py", line 44, in <module>
    cplex_input.write("saved_models/"+name+".lp", "lp")
  File "C:\ProgramData\Anaconda3\lib\site-packages\cplex\__init__.py", line 989, in write
    _proc.writeprob(self._env._e, self._lp, filename, filetype)
  File "C:\ProgramData\Anaconda3\lib\site-packages\cplex\_internal\_procedural.py", line 791, in writeprob
    check_status(env, status)
  File "C:\ProgramData\Anaconda3\lib\site-packages\cplex\_internal\_procedural.py", line 236, in __call__
    raise CplexSolverError(error_string, env, status)
cplex.exceptions.errors.CplexSolverError: CPLEX Error  1422: Could not open file 'saved_models/problematic_tree_1.lp' for writing.   
PS C:\Users\sarah\Documents\These\Sub-problems\2-tiles\Tree\Programmation\2-tile>
```

**Comment by laowantong** [comment]
Rien ne me saute vraiment aux yeux, à déboguer pas à pas sans doute.

**Comment by SarahMinich** [comment]
Pour le moment, ça n'a pas l'air d'être après le même nombre d'itérations que le programme plante et ça n'a pas l'air non plus lié à une taille trop élevée (j'ai essayé avec un nombre de noeuds maximum égal à 15 -alors que le problème sait traiter des instances plus grosses- et le programme a planté avec seulement 7 noeuds après trois itérations).
